name: OS Compatibility
on: [push, pull_request]
jobs:
  build:
    name: "Compatibility: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [8] # Minimum supported major version
        os: [ubuntu-latest, windows-latest] # All supported OS
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: ${{ matrix.java }}
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test
